"Added error state & util func for avatar name"
13prashant/concert-management pull request #7
Opened 2022-08-01 04:43 UTC by Nishantchavda36

2022-08-01 14:26 UTC, 13prashant requested changes

2022-08-01 14:26 UTC, 13prashant commented on src/pages/createConcert/CreateConcert.js
> +  const handleSubmit = async (e) => {
In useFirestore hook make addDocument function and call it from there by passing required params. Which will be more reusable. And also manage data, error, isPending states there only.

2022-08-01 14:26 UTC, 13prashant commented on src/pages/createConcert/CreateConcert.js
> +        console.error('Error adding document: ', e);
Need to show in UI. For that you can find Error component in components.

2022-08-02 16:00 UTC, Nishantchavda36 commented
> 

Can we merge this branch??

2022-08-02 16:12 UTC, merged